### PR TITLE
 adding quit and counter to UI

### PR DESCRIPTION
**Pull request by squeakus**
This is my first time hand labelling so I needed to add a counter to give me a sense of progress :)

### CODE REVIEW

**Comment by matpalm** [comment]
Thanks! I'm away for a few weeks so will meet when I get back

**Comment by matpalm** [comment]
thanks again for the PR !

i noticed your change included a change to the default height / width, i just cleaned that up in 25fab392b4d7a63324d2227265a2bc44221de977

**Comment by squeakus** [comment]
You're welcome! I plan on booking some free time next month and trying this project out properly, so hopefully there will be more PRs to follow. I also managed to stretch my wifi out to my bees so I can stream more data and build up a bigger dataset. Once I have it gathered I will add it to kaggle.

**Comment by matpalm** [comment]
i notice you work at movidius, awesome! 

definitely let me know when you get the point of wanting to run a model on compute stick, i had some problems and would love to see what i did wrong

see [this forum post](https://ncsforum.movidius.com/discussion/692/incorrect-inference-results-from-a-minimal-tensorflow-model#latest) for repro info

**Comment by squeakus** [comment]
Indeed I do! I am working on the research team and came across your post and thought it was an excellent application and a chance for me to get familiar with the NCS technology. If I can count my bees and fix a bug at the same time it is killing two birds with one stone! I reached out to the NCS dev team and they are going to help in any way they can.

**Pull request merged**
