### PR TITLE
checking images, automatically computingsize, shortening command line args

### PR DESCRIPTION
**Pull request by squeakus**
i hit a bunch of problems with the size of my images in my dataset. I added a function in util that checks the image, ensures all sizes are matching and returns the size.

I also added some command line flags and a little script for scp-ing images if your bees are lucky enough to have internet :)

I'm just trying to get my head around the code so I won't be offended if you reject these changes. I have started training now and i'm really excited to see how the semi-supervised learning works out. It took a lot longer than expected to set up the data collection but now I have images pouring in and I plan on updating the kaggle dataset once they are labelled.

### CODE REVIEW

**Comment by matpalm** [comment]
thanks for the PR! i totally get that the width/height stuff is a complete pain in the ass but there's a reason that we don't want to check all image size consistency; it's still work in progress but i'll try to explain why...

so this network is fully convolutional which means we can try in one resolution and test in another. the main way i've been training this is not on the full resolution image but instead with patches. for awhile i did this as fractions of the original image size (`--patch-fraction`) but have just changed to fixed square patches (`--patch-width-height`). the reason for doing this is that if you're training only on patches it means the input images don't have to all be the same resolution/aspect & this is the main way i'm doing training, it's across a mix of peoples datasets, of varying resolutions & aspect ratios .

square patches is also related to a branch, i'm still working on, that does [domain adversarial training](https://arxiv.org/abs/1505.07818) where there are three networks in train.py; the main (rgb->bitmap) network, the test version of the same network and an additional third network that goes from rgb -> e4 -> binary classifier (with gradient reversal). this third network also operates on square patches since i've found that having the DA path work on the same size inputs as the main training path has been things a lot easier to visualise; specifically the gradient interactions at e4...   (not sure how much of this kind of thing you've played with?)

thirdly i've got _another_ branch which is playing with [MAML](https://arxiv.org/abs/1703.03400) and, again, working on fixed sized patches makes everything much much easier to work through...

does that all make sense? i'm happy to merge across the util function (and not use it myself) if it makes things easier?

**Comment by squeakus** [comment]
Hi Mat, that makes perfect sense and I will defer to your master plan :) There is no need to merge as I can keep working on my fork and familiarizing myself with the code without breaking yours. It turns out the problem I was having was not to do with mixed image sizes but a rounding error caused by resizing an image to something indivisible by 4 which messed up the layers in the model.

Anyways that is fixed now and I am getting an F1 score of .78 on 500 labelled images. There are a lot of false negatives but I think this is because im using macro images of bees rather than the medium distance of your sample images. I hope to have my head around the code by the end of the week and replicating the ncs bugs by next week, I will keep you posted!

**Comment by matpalm** [comment]
i'd tuned to average size of my bees but if your bees occupy a much larger area you can increase the receptive field of the encoder part of the network. 

easiest way is to increase the kernel size of the first few convolutions (i.e. say, kernel_size (K)=5 for e1 and e2, or maybe K=7 for e1 and K=5 for e2, or whatever makes sense from experiments) this will increase parameter counts, but not hugely. 

if you're keen to keep the parameters low (which is fair for deployment to the NCS) when you increase K you can also increase the stride (from 2 to say 4). this will though change the shapes so, if you're using skip connections, you'll have to ensure that the nearest neighbour upsizing sizes match...

( actually, on second thought, it might just be simpler to use dilation here... if the NCS supports it? would have to check... )

**Comment by matpalm** [comment]
merged just `rasp_pi/capture_and_send.sh` and your util method in 4af6b0a

**Comment by matpalm** [comment]
( let me know when you get to reproing the NCS bugs i had; hopefully it's just the old SDK or some silly problem on my end... note: this network is using nearest neighbour resizing for the upsampling step but, as i understand it, there isn't an op for this in the movidius compiler... i have an old branch that includes a version of this using deconvolutions instead for the upsampling so i can resurrect that too if need be )

**Comment by squeakus** [comment]
Thank you for the advice, I will try out a bigger kernel when I get home. This will be my first attempt using the NCSDK other than the standard pre-baked networks but a colleague will be helping me when he gets back next week. Hopefully I will have something for you by Friday next.

**Pull request closed without merging**
